
# All the numerics we are going to use.

from math import *
from models import *

MODEL_LIST=[RooflineModel(),CommunicationModel(),AmdahlModel(),GeneralModel(),PowerComModel()]
#MODEL_LIST=[GeneralModel()]
Heuristics=["ICPP22", "TOPC24", "Fair", "minTime", "minArea"]
#Heuristics=["Amin", "CP"]
parameters=["Regular","Density","Fat","n","P", "Priority","Jump"]  
#parameters=["n"]


nb_iterations =50 #Number of experients for any set of parameters
alpha=0

USEWDAG=True #If set to true, the w used will be the one generated by daggen. If set to False, the w will be randomly generated as below
p_bounds=[1,512]    #If value is changed, must be changed manually in PowerComModel models.py
w_bounds=[2,5] #Between 10^2 and 10^5 
d_bounds=[-3,-0.5] #Between 10^-3 and 10^-0.5
c_bounds=[-6,-2] #Between 10^-6 and 10^-2



#This should be extremely flexible, you can add values, remove values, PMain don't have to be in p_list = [256, 384, 512, 640, 768, 896, 1024], etc
priority_list=["FIFO","procs","area","length"]
priorityMain="FIFO"
mu_list=[0.1,0.15, 0.2, 0.25, 0.3,0.35, 0.4,0.45, 0.5]
mumain=0
p_list = [124, 256, 384, 512, 640, 768, 896, 1024]
#p_list = [12, 25, 38, 51, 64, 76, 89, 102]
PMain= 512
logP=False # For display, set to True if you test like [256,512,1024,2048,4096]
n_list = [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000] 
#n_list = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500] 
nMain=2500
jump_list = [1, 2, 3, 4, 5, 6, 7, 8,9]  
jumpMain=5
fat_list=[0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
#fat_list =[0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1] 
fatMain=0.5
density_list=[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7]
#density_list =[0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1] 
densMain=0.5
regular_list = [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1] 
regMain=0.5

