
# All the numerics we are going to use.

from math import *
from models import *

#MODEL_LIST=[GeneralModel(),AmdahlModel(),CommunicationModel(),RooflineModel(),Power25Model(),Power50Model(),Power75Model(),Power100Model()]
MODEL_LIST=[GeneralModel(),AmdahlModel(),CommunicationModel(),RooflineModel(),Power25Model(),Power50Model(),Power75Model(),Power100Model()]
parameters=["Regular","Density","Fat","n","P", "Priority","Jump"]
#parameters=["Regular"]
Heuristics=["ICPP22", "TOPC24", "minTime"]#, "Amin", "ATmin","CP"]
#Heuristics=["Amin", "CP"]
nb_iterations =1
alpha=0
mu=0


USEWDAG=True #If set to true, the w used will be the one generated by daggen. If set to False, the w will be randomly generated in 10^x for x uniform in [3,6]

w_bounds=[2,5]
p_bounds=[1,640]
d_bounds=[-3,-0.5]
c_bounds=[-6,-2]


priority_list=["length","FIFO","area","procs","random"]
priorityMain="FIFO"
p_list = [256, 384, 512, 640, 768, 896, 1024]
PMain= 640
logP=False
n_list = [1000, 2000, 3000, 4000, 5000] 
nMain=3000
jump_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]  
jumpMain=5
fat_list = [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
fatMain=0.7
density_list = [0, 0.1, 0.2, 0.3, 0.4, 0.5,0.6] 
densMain=0.3
regular_list = [0, 0.2, 0.4, 0.6, 0.8, 1] 
regMain=0.5

